Будем работать с датасетом Pima Indian Diabetes - это набор данных из Национального института диабета, болезней органов пищеварения и почек. Целью набора данных является диагностическое прогнозирование наличия диабета у пациента. Несколько ограничений были наложены на выбор этих экземпляров из большой базы данных. В частности, все пациенты здесь - женщины в возрасте от 21 года, индийского происхождения.

Описание данных:Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, Age

- __Pregnancies__ - данная единица отображает количество беременностей, единицы измерения - целые числа от 0 до N. Тип переменной - количественная, дискретная.
- __Glucose__ - данная единица отображает уровень глюкозы в крови, единицы измерения - целые числа. Тип переменной - количественная, дискретная.
- __BloodPressure__ - данная единица отображает артериальное давление, единицы измерения - миллиметры р/с, целые числа. Тип переменной - количественная, дискретная.
- __SkinThickness__ - данная единица отображает обхват трицепса в миллиметрах, целые числа. Тип переменной - количественная, дискретная.
- __Insulin__ - данная единица отображает уровень инсулина в крови, целые числа. Тип переменной - количественная, дискретная.
- __BMI__ - данная единица отображает индекс массы тела. Тип переменной - количественная, непрерывная.
- __DiabetesPedigreeFunction__ - данная единица отображает риск наследственного диабета в зависимости наличия диабета у родственников. Выражается десятичной дробью от 0 до 1. Тип переменной - количественная, непрерывная.
- __Age__ - данная единица отражает возраст в целых числах. Тип переменной - количественная, дискретная.
- __Class__ - данная единица отражает наличие диабета у субъекта, выражена 0(здоров) или 1(болен). Тип переменной - категориальная, бинарная.

In [ ]:
# Подключение библиотек
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/dataset_diabet.csv')
df.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0

In [ ]:
df.columns = df.columns.str.lower()

**Задание 1.** Посчитайте количество пропусков в каждом из столбцов.

In [ ]:
#Ваш код здесь
# 1. способ метод info()
df.info()

# 2. использование цепочки методов isna().sum или isnull().sum
df.isna().sum()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pregnancies               768 non-null    int64
 1   glucose                   763 non-null    float64
 2   bloodpressure             733 non-null    float64
 3   skinthickness             541 non-null    float64
 4   insulin                   394 non-null    float64
 5   bmi                       757 non-null    float64
 6   diabetespedigreefunction  768 non-null    float64
 7   age                       768 non-null    int64
 8   class                     768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

pregnancies                   0
glucose                       5
bloodpressure                35
skinthickness               227
insulin                     374
bmi                          11
diabetespedigreefunction      0
age                           0
class                         0
dtype: int64

**Задание 2.** Замените все пропуски дискретных признаков соответствующими медианами, непрерывных признаков - средними значениями.

In [ ]:
# Ваш код здесь
# для заполнения пропусков воспользуйтесь методом fillna()

# дискретных -- медианами
# непрерывных -- средними

# Pregnancies -- дискретная.
# Glucose -- дискретная.
# BloodPressure дискретная.
# SkinThickness -- дискретная.
# Insulin -- дискретная.
# BMI - непрерывная.
# DiabetesPedigreeFunction - непрерывная.
# Age дискретная.
# Class дискретная


values = {'glucose': df.glucose.median(),
          'bloodpressure': df.bloodpressure.median(),
          'skinthickness': df.skinthickness.median(),
          'insulin': df.insulin.median(),
          'bmi': df.bmi.mean()}

df.fillna(value=values,
          inplace=True)

In [ ]:
df.isna().sum()

pregnancies                 0
glucose                     0
bloodpressure               0
skinthickness               0
insulin                     0
bmi                         0
diabetespedigreefunction    0
age                         0
class                       0
dtype: int64

**Задание 3.** Вычислите основные статистики (минимум, максимум, среднее, дисперсию, квантили) для всех столбцов.

In [ ]:
#Ваш код здесь

df.describe()

df.agg(['min', 'max', 'mean', 'var'])

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,class
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000
mean,3.845052,121.656250,72.386719,29.108073,140.671875,32.457464,0.471876,33.240885,0.348958
var,11.354056,926.489244,146.328741,77.285567,7462.033002,47.267706,0.109779,138.303046,0.227483

In [ ]:
np.percentile(df.pregnancies, 45)
print(np.nanpercentile(df.pregnancies, 99),
    np.nanpercentile(df.pregnancies, 90),
np.nanpercentile(df.pregnancies, 80),
np.nanpercentile(df.pregnancies, 70),
np.nanpercentile(df.pregnancies, 60),
np.nanpercentile(df.pregnancies, 50),
np.nanpercentile(df.pregnancies, 40))

13.0 9.0 7.0 5.0 4.0 3.0 2.0

**Задание 4.** У скольких женщин старше 50 лет обнаружен диабет?

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pregnancies               768 non-null    int64
 1   glucose                   768 non-null    float64
 2   bloodpressure             768 non-null    float64
 3   skinthickness             768 non-null    float64
 4   insulin                   768 non-null    float64
 5   bmi                       768 non-null    float64
 6   diabetespedigreefunction  768 non-null    float64
 7   age                       768 non-null    int64
 8   class                     768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

In [ ]:
df = df.rename(columns={'class': 'diabet'})

In [ ]:
#Ваш код здесь
#У скольких женщин старше 50 лет обнаружен диабет?
req = (df.age > 50) & (df.diabet == 1)
df.loc[req]
df[(df.age > 50) & (df.diabet == 1)].shape[0]
df[req]
df.query('age > 50 & diabet == 1').shape[0]
len(df.query('age > 50 & diabet == 1'))

38

**Задание 5.** Найдите трех женщин с наибольшим числом беременностей.

In [ ]:
df.loc[df.pregnancies.nlargest(3).index]

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,diabet
159,17,163.0,72.0,41.0,114.0,40.9,0.817,47,1
88,15,136.0,70.0,32.0,110.0,37.1,0.153,43,1
298,14,100.0,78.0,25.0,184.0,36.6,0.412,46,1

In [ ]:
#Ваш код здесь
df.sort_values(by=['pregnancies']).tail(3)
df.sort_values(by=['pregnancies'],
               ascending=False).head(3)
df.pregnancies.nlargest(3)
df.pregnancies.nlargest(3).index
df.loc[df.pregnancies.nlargest(3).index]
df.sort_values(by=['pregnancies'],
               ascending=False)[:3]
df.loc[[159, 88, 298]]
df.iloc[[159, 88, 298]]


dict_df = {'col1': [1,2,3,4,5,6,7,8,9], 'col2': [11,12,13,14,15,16,17,18,19]}
pd.DataFrame(dict_df,
             index=['а','б','в','г','д','е','и','з','к'])

   col1  col2
а     1    11
б     2    12
в     3    13
г     4    14
д     5    15
е     6    16
и     7    17
з     8    18
к     9    19

**Задание 6.** Сколько женщин возраста между 30 и 40 успело родить 3 или более детей?

In [ ]:
#Ваш код здесь
req = (df.age.between(30,40)) & (df.pregnancies>=3)
df.loc[req]
df[req]
df.query('age.between(30,40) & pregnancies>=3').shape[0]

print(f"""Женщин возраста между 30 и 40
успело родить 3 или более детей
равно {df.query('age.between(30,40) & pregnancies>=3').shape[0]}""")

Женщин возраста между 30 и 40
успело родить 3 или более детей
равно 142

In [ ]:
 df.loc[(df.age.between(30,40)) & (df.pregnancies >=3)].shape[0]

142

**Задание 7.** Нормальным кровяным давлением будем считать давление в диапазоне [80-89]. У какого процента женщин давление нормальное?

In [ ]:
#Ваш код здесь
req = df.bloodpressure.between(80,89)

np.round(df.loc[req].shape[0] / df.shape[0] * 100, 2)
print(f'Процент женщин с нормальным давлением {df.loc[req].shape[0] / df.shape[0]:.2%}')

Процент женщин с нормальным давлением 18.88%

**Задание 8.** Считается, что BMI >= 30 - это признак ожирения.
У скольких женщин с признаками ожирения кровяное давление выше среднего?

In [ ]:
#Ваш код здесь

req = (df.bmi>=30) & (df.bloodpressure>df.bloodpressure.mean())
df.loc[req].shape[0]

251

**Задание 9.** Сравните средние значения для признаков __Glucose,	BloodPressure,	Insulin__ среди тех, у кого обнаружен диабет, и тех, у кого его нет.

In [ ]:
#Ваш код здесь
pd.pivot_table(data=df,
               index='diabet',
               values=['glucose', 'bloodpressure', 'insulin'],
               aggfunc='mean')


#    Glucose, BloodPressure, Insulin
# 0    56         5             58
# 1

df.groupby('diabet').agg(glucose_mean=('glucose', 'mean'),
                         bloodpressure_mean=('bloodpressure', 'mean'),
                         insulin_mean=('insulin', 'mean')).reset_index()

   diabet  glucose_mean  bloodpressure_mean  insulin_mean
0       0    110.682000           70.920000    127.792000
1       1    142.130597           75.123134    164.701493

**Задание 10.** Добавьте новый бинарный признак:

__wasPregnant__ $\in$ {0,1} - была женщина беременна (1) или нет (0)

In [ ]:
#можно написать функцию
def wasPregnant(x):
    if x>0:
        return 1
    else:
        return 0

In [ ]:
df['wasPregnant'] = df.pregnancies.apply(wasPregnant)

In [ ]:
df.head(2)

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,diabet,wasPregnant
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1,1
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0,1

In [ ]:
#можно с использование метода where из библиотеки numpy
df['wasPregnant_two'] = np.where(df['pregnancies']>0, 1, 0)

In [ ]:
df.head(2)

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,diabet,wasPregnant,wasPregnant_two
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1,1,1
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0,1,1

**Задание 11.** Сравните процент больных диабетом среди женщин, которые были беременны и не были.

In [ ]:
# Общее количество больных беременных / Общее количество больных
# Общее количество больных не беременных / Общее количество больных

a = round(df[(df.Pregnancies > 0) & (df.Class == 1)].shape[0] / df[df.Class == 1].shape[0]*100, 2)
b = round(df[(df.Pregnancies == 0) & (df.Class == 1)].shape[0] / df[df.Class == 1].shape[0]*100, 2)
print(a, b)

85.82 14.18

**Задание 12.** Добавьте новый категориальный признак __bodyType__ на основе столбца BMI:

__BMI Categories:__

Underweight = <18.5

Normal weight = 18.5–24.9

Overweight = 25–29.9

Obesity = BMI of 30 or greater

Признак должен принимать значения Underweight, Normal weight, Overweight и Obesity.

In [ ]:
#Ваш код здесь
def func_body_type(x):
    if x <= 18.5:
        return 'Underweight'
    elif (x > 18.5) & (x<=24.9):
        return 'Normal weight'
    elif (x >= 25) & (x<=29.9):
        return 'Overweight'
    else:
        return 'Obesity'

In [ ]:
df['bodyType'] = df.bmi.apply(func_body_type)

In [ ]:
df.head(2)

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,diabet,wasPregnant,wasPregnant_two,bodyType
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1,1,1,Obesity
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0,1,1,Overweight

**Задание 13.** Будем считать "здоровыми" тех, у кого нормальный вес и кровяное давление. Какой процент "здоровых" женщин больны диабетом?

In [ ]:
# req1 = (df.diabet == 1)
# req2 = (df.bodyType == 'Normal weight') & (df.bloodpressure.between(80,89)) & (df.diabet == 1)
()&()&()

req1 = ((df.bodyType == 'Normal weight') &
     (df.bloodpressure.between(80,89)))
req2 = (
    (df.bodyType == 'Normal weight') &
     (df.bloodpressure.between(80,89)) &
      (df.diabet == 1)
)



df.loc[req2].shape[0] / df[req1].shape[0] *100

10.0

In [ ]:
#Ваш код здесь

In [ ]:
df.head(2)

,client_id,gender,age,marital_status,job_position,credit_sum,credit_month,score_shk,education,tariff_id,living_region,okrug,avregzarplata,monthly_income,credit_count,overdue_credit_count,open_account_flg,date_bank
0,1,2,48.0,3.0,15,59998,10,"0,770249",2.0,28,23.0,8.0,25850.0,30000.0,1.0,1.0,0,2016-02-16 18:54:34
1,2,1,28.0,NaN,15,10889,6,"0,248514",2.0,2,30.0,7.0,66880.0,43000.0,2.0,0.0,0,2016-02-15 12:39:04

In [ ]:
#пишем функцию по замене `,` на `.`
def swap_comma(x):
    return float(str(x).replace(',', '.'))

In [ ]:
#применяем функцию к столбцу с суммами кредитов и создаем новый столбец
df['new_credit_sum'] = df.credit_sum.apply(swap_comma)

In [ ]:
#проверяем себя
df[['credit_sum', 'new_credit_sum']].head(10)

  credit_sum  new_credit_sum
0      59998        59998.00
1      10889        10889.00
2      10728        10728.00
3   12009,09        12009.09
4   16908,89        16908.89
5      26788        26788.00
6      10317        10317.00
7      47878        47878.00
8   37577,16        37577.16
9      26268        26268.00

In [ ]:
!pip install PyQt6

Collecting PyQt6
  Downloading PyQt6-6.5.2-cp37-abi3-manylinux_2_28_x86_64.whl (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 20.0 MB/s eta 0:00:00
Collecting PyQt6-sip<14,>=13.4 (from PyQt6)
  Downloading PyQt6_sip-13.5.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.whl (298 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 299.0/299.0 kB 28.0 MB/s eta 0:00:00
Collecting PyQt6-Qt6>=6.5.0 (from PyQt6)
  Downloading PyQt6_Qt6-6.5.2-py3-none-manylinux_2_28_x86_64.whl (66.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 MB 10.6 MB/s eta 0:00:00
Installing collected packages: PyQt6-Qt6, PyQt6-sip, PyQt6
Successfully installed PyQt6-6.5.2 PyQt6-Qt6-6.5.2 PyQt6-sip-13.5.2

In [ ]:
import sys
from PyQt6.QtWidgets import QApplication, QWidget

class EmptyWindow(QWidget):
    def __init__(self):
        """ Constructor for Empty Window Class """
        super().__init__()
        self.initializeUI()

        def initializeUI(self):
            """Set up the application."""
            self.setGeometry(200, 100, 400, 300)
            self.setWindowTitle("Empty Window in PyQt")
            self.show() # Display the window on the screen

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = EmptyWindow()
    sys.exit(app.exec())