Задание 7. Исследовательский анализ данных на языке Python

Инструкция:

Шаг 1.  Изучите материалы лекционных и практических занятий по темам раздела 4.

Шаг 2. Выполните исследовательский анализ данных EDA по предложенному датасету (Алгоритм выполнения представлен в практическом занятии по теме 4.3).

Шаг 3. Опубликуйте файл расширения ipynb на платформе Odin.

ЗАДАНИЕ


Клиентам предлагают два тарифных плана: «Смарт» и «Ультра». Необходимо сделать предварительный анализ тарифов на небольшой выборке клиентов -- 500 пользователей. Нужно проанализировать поведение клиентов и сделать вывод — какой тариф лучше.

**Описание тарифов**

|**Услуги**|**Тариф «Смарт»**|**Тариф «Ультра»**|
|:------|:------|:-----|
Ежемесячная плата | 550 рублей| 1950 рублей|
Включено | 500 минут разговора, 50 сообщений и 15 Гб интернет-трафика| Включено 3000 минут разговора, 1000 сообщений и 30 Гб интернет-трафика|
Стоимость услуг сверх тарифного пакета | минута разговора: 3 рубля; сообщение: 3 рубля; 1 Гб интернет-трафика: 200 рублей | минута разговора: 1 рубль; сообщение: 1 рубль; 1 Гб интернет-трафика: 150 рублей|

Обратите внимание: Компания всегда округляет вверх значения минут и мегабайтов. Если пользователь проговорил всего 1 секунду, в тарифе засчитывается целая минута.

**Имеются следующие таблицы**

Таблица `users` (информация о пользователях):

|Имя поля|Описание поля|
|-------------:|:------------|
|**user_id** | уникальный идентификатор пользователя|
|**first_name** | имя пользователя|
|**last_name** | фамилия пользователя|
|**age** | возраст пользователя (годы)|
|**reg_date** | дата подключения тарифа (день, месяц, год)|
|**churn_date** | дата прекращения пользования тарифом (если значение пропущено, то тариф ещё действовал на момент выгрузки данных)|
|**city** | город проживания пользователя|
|**tariff** | название тарифного плана|

Таблица `calls` (информация о звонках):

|Имя поля|Описание поля|
|-------------:|:------------|
|**id** | уникальный номер звонка|
|**call_date** | дата звонка|
|**duration** | длительность звонка в минутах|
|**user_id** | идентификатор пользователя, сделавшего звонок|

Таблица `messages` (информация о сообщениях):

|Имя поля|Описание поля|
|-------------:|:------------|
|**id** | уникальный номер сообщения|
|**message_date** | дата сообщения|
|**user_id** |  идентификатор пользователя, отправившего сообщение|

Таблица `internet` (информация об интернет-сессиях):

|Имя поля|Описание поля|
|-------------:|:------------|
|**id** | уникальный номер сессии|
|**mb_used** | объём потраченного за сессию интернет-трафика (в мегабайтах)|
|**session_date** | дата интернет-сессии|
|**user_id** | идентификатор пользователя|

Таблица `tariffs` (информация о тарифах):

|Имя поля|Описание поля|
|-------------:|:------------|
|**tariff_name** | название тарифа|
|**rub_monthly_fee** | ежемесячная абонентская плата в рублях|
|**minutes_included** | количество минут разговора в месяц, включённых в абонентскую плату|
|**messages_included** | количество сообщений в месяц, включённых в абонентскую плату|
|**mb_per_month_included** | объём интернет-трафика, включённого в абонентскую плату (в мегабайтах)|
|**rub_per_minute** | стоимость минуты разговора сверх тарифного пакета (например, если в тарифе 100 минут разговора в месяц, то со 101 минуты будет взиматься плата)|
|**rub_per_message** | стоимость отправки сообщения сверх тарифного пакета|
|**rub_per_gb** | стоимость дополнительного гигабайта интернет-трафика сверх тарифного пакета (1 гигабайт = 1024 мегабайта)|


Инструкция по выполнению проекта

**Шаг 1. Откройте файл с данными и изучите общую информацию**

-загрузите файлы и изучите общую информацию;

**Шаг 2. Подготовьте данные**
- Приведите данные к нужным типам;
- Найдите и исправьте ошибки в данных. Обратите внимание, что длительность многих звонков — 0.0 минут.  
- Посчитайте для каждого пользователя:
    - количество сделанных звонков и израсходованных минут разговора по месяцам;
    - количество отправленных сообщений по месяцам;
    - объем израсходованного интернет-трафика по месяцам;
    - помесячную выручку с каждого пользователя (вычтите бесплатный лимит из суммарного количества звонков, сообщений и интернет-трафика; остаток умножьте на значение из тарифного плана; прибавьте абонентскую плату, соответствующую тарифному плану);
    - найдите общую сумму затрат всех клиентов за все время.


    АНОМАЛИИ - не обрабатываем.

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
#первый способ чтения данных из нескольких датафреймов
#просто считаем каждый файл в отдельный датафрейм

df_users = pd.read_csv('/content/users.csv')
df_calls = pd.read_csv('/content/calls.csv')
df_messages = pd.read_csv('/content/messages.csv')
df_internet = pd.read_csv('/content/internet.csv')
df_tariffs = pd.read_csv('/content/tariffs.csv')

In [15]:
# Предобработка
# корректировка типов
df_users = df_users.astype({'reg_date': 'datetime64'})
df_calls = df_calls.astype({'call_date': 'datetime64'})
df_messages = df_messages.astype({'message_date': 'datetime64'})
df_internet = df_internet.astype({'session_date': 'datetime64'})

In [16]:
#удаление столбца
df_internet.drop(columns='Unnamed: 0',
                 inplace=True)

In [20]:
df_calls['duration'] = np.ceil(df_calls['duration'])

In [21]:
#выделим месяц
import datetime as dt
df_calls['year_month'] = df_calls['call_date'].dt.to_period('M')
#количество сделанных звонков и израсходованных минут разговора по месяцам;
df_user_month = df_calls.groupby(['user_id', 'year_month'])\
        .agg(count_call_user_month=('id', 'count'),
             sum_duration_user_month=('duration', 'sum')).reset_index()

In [24]:
df_user_month.head(2)

   user_id year_month  count_call_user_month  sum_duration_user_month
0     1000    2018-05                     22                    159.0
1     1000    2018-06                     43                    172.0

In [23]:
#количество отправленных сообщений по месяцам;
#выделить из даты месяц в формате год-месяц
df_messages
df_messages['year_month'] = df_messages['message_date'].dt.to_period('M')
df_message_month = df_messages.groupby(['user_id', 'year_month'])\
.agg(count_messages=('id', 'count'))\
.reset_index()\
.merge(df_users[['user_id', 'first_name', 'last_name']],
       on='user_id')
df_message_month.head(2)

   user_id year_month  count_messages first_name  last_name
0     1000    2018-05              22     Рафаил  Верещагин
1     1000    2018-06              60     Рафаил  Верещагин

In [27]:
#объем израсходованного интернет-трафика по месяцам;
df_internet['year_month'] = df_internet['session_date'].dt.to_period('M')
df_internet_month = df_internet.groupby(['user_id', 'year_month'])\
.agg(volume_traffic=('mb_used', 'sum'))\
.reset_index()\
.merge(df_users[['user_id', 'first_name', 'last_name']],
       on='user_id')

In [33]:
df_user_month.shape[0]

3174

In [35]:
df_message_month.shape[0]

2717

In [30]:
df_user_month.head(1)

   user_id year_month  count_call_user_month  sum_duration_user_month
0     1000    2018-05                     22                    159.0

In [31]:
df_message_month.head(1)

   user_id year_month  count_messages first_name  last_name
0     1000    2018-05              22     Рафаил  Верещагин

In [32]:
df_internet_month.head(1)

   user_id year_month  volume_traffic first_name  last_name
0     1000    2018-05         2253.49     Рафаил  Верещагин

In [37]:
df_call_messages_internet_agg = df_user_month[['user_id', 'year_month', 'count_call_user_month', 'sum_duration_user_month']]\
                                .merge(df_message_month[['user_id', 'year_month', 'count_messages']],
                                                     on=('user_id', 'year_month'), how='outer')\
                                .merge(df_internet_month[['user_id', 'year_month', 'volume_traffic']],
                                                     on=('user_id', 'year_month'), how='outer')
df_call_messages_internet_agg

,user_id,year_month,count_call_user_month,sum_duration_user_month,count_messages,volume_traffic
0,1000,2018-05,22.0,159.0,22.0,2253.49
1,1000,2018-06,43.0,172.0,60.0,23233.77
2,1000,2018-07,47.0,340.0,75.0,14003.64
3,1000,2018-08,52.0,408.0,81.0,14055.93
4,1000,2018-09,58.0,466.0,57.0,14568.91
...,...,...,...,...,...,...
3209,1489,2018-09,NaN,NaN,32.0,17206.30
3210,1489,2018-10,NaN,NaN,21.0,19559.44
3211,1489,2018-11,NaN,NaN,20.0,17491.56
3212,1489,2018-12,NaN,NaN,35.0,17322.51
3213,1476,2018-04,NaN,NaN,NaN,530.78

In [41]:
df_call_messages_internet_agg.fillna({'count_call_user_month': 0,
                                      'sum_duration_user_month': 0,
                                      'count_messages': 0,
                                      'volume_traffic': 0}, inplace=True)

In [42]:
df_call_messages_internet_agg.isna().sum()

user_id                    0
year_month                 0
count_call_user_month      0
sum_duration_user_month    0
count_messages             0
volume_traffic             0
dtype: int64

In [44]:
df = df_call_messages_internet_agg.merge(df_users[['user_id', 'first_name', 'last_name', 'tariff']],
                                         on='user_id')

In [49]:
df.head(5)

,user_id,year_month,count_call_user_month,sum_duration_user_month,count_messages,volume_traffic,first_name,last_name,tariff
0,1000,2018-05,22.0,159.0,22.0,2253.49,Рафаил,Верещагин,ultra
1,1000,2018-06,43.0,172.0,60.0,23233.77,Рафаил,Верещагин,ultra
2,1000,2018-07,47.0,340.0,75.0,14003.64,Рафаил,Верещагин,ultra
3,1000,2018-08,52.0,408.0,81.0,14055.93,Рафаил,Верещагин,ultra
4,1000,2018-09,58.0,466.0,57.0,14568.91,Рафаил,Верещагин,ultra

In [47]:
df_tariffs

,messages_included,mb_per_month_included,minutes_included,rub_monthly_fee,rub_per_gb,rub_per_message,rub_per_minute,tariff_name
0,50,15360,500,550,200,3,3,smart
1,1000,30720,3000,1950,150,1,1,ultra

In [55]:
ЕСЛИ()max(159.0 - 3000, 0)*1 + np.ceil(max(2253.49 - 30720, 0)/1024)*150 + max(22.0 - 1000, 0)*1 + 1950

1600.0

In [61]:
df_tariffs.loc[df_tariffs['tariff_name']=='ultra', 'minutes_included'].iloc[0]

3000

In [58]:
def month_calc(name_df):
    calls = name_df['sum_duration_user_month']
    messages = name_df['count_messages']
    internet = name_df['volume_traffic']
    tariff = name_df['tariff']
    # достанем лимиты по тарифам на звонки, смс и интернет
    minutes_lim = df_tariffs.loc[df_tariffs['tariff_name'] == tariff, 'minutes_included'].iloc[0]
    messages_lim = df_tariffs.loc[df_tariffs['tariff_name'] == tariff, 'messages_included'].iloc[0]
    internet_lim = df_tariffs.loc[df_tariffs['tariff_name'] == tariff, 'mb_per_month_included'].iloc[0]
    # переплата по звонкам
    call_overlimit = max(calls - minutes_lim, 0)
    call_overpay = call_overlimit * df_tariffs.loc[df_tariffs['tariff_name'] == tariff, 'rub_per_minute'].iloc[0]
    # # переплата по сообщениям
    messages_overlimit = max(messages - messages_lim, 0)
    messages_overpay = messages_overlimit * df_tariffs.loc[df_tariffs['tariff_name'] == tariff, 'rub_per_message'].iloc[0]
    # # переплата за трафик интернета
    internet_overlimit = max(internet - internet_lim, 0)
    internet_overpay = np.ceil(internet_overlimit/1024)*df_tariffs.loc[df_tariffs['tariff_name'] == tariff, 'rub_per_gb'].iloc[0]
    return (call_overpay + messages_overpay + internet_overpay+\
           df_tariffs.loc[df_tariffs['tariff_name'] == tariff, 'rub_monthly_fee'].iloc[0])

In [59]:
df['monthly_profit_each_user'] = df.apply(month_calc, axis=1)

In [63]:
df.head(50)

,user_id,year_month,count_call_user_month,sum_duration_user_month,count_messages,volume_traffic,first_name,last_name,tariff,monthly_profit_each_user
0,1000,2018-05,22.0,159.0,22.0,2253.49,Рафаил,Верещагин,ultra,1950.0
1,1000,2018-06,43.0,172.0,60.0,23233.77,Рафаил,Верещагин,ultra,1950.0
2,1000,2018-07,47.0,340.0,75.0,14003.64,Рафаил,Верещагин,ultra,1950.0
3,1000,2018-08,52.0,408.0,81.0,14055.93,Рафаил,Верещагин,ultra,1950.0
4,1000,2018-09,58.0,466.0,57.0,14568.91,Рафаил,Верещагин,ultra,1950.0
5,1000,2018-10,57.0,350.0,73.0,14702.49,Рафаил,Верещагин,ultra,1950.0
6,1000,2018-11,43.0,338.0,58.0,14756.47,Рафаил,Верещагин,ultra,1950.0
7,1000,2018-12,46.0,333.0,70.0,9817.61,Рафаил,Верещагин,ultra,1950.0
8,1001,2018-11,59.0,430.0,0.0,18429.34,Иван,Ежов,smart,1150.0
9,1001,2018-12,63.0,414.0,0.0,14036.66,Иван,Ежов,smart,550.0
10,1002,2018-06,15.0,117.0,4.0,10856.82,Евгений,Абрамович,smart,550.0
11,1002,2018-07,26.0,214.0,11.0,17580.10,Евгений,Абрамович,smart,1150.0
12,1002,2018-08,42.0,289.0,13.0,20319.26,Евгений,Абрамович,smart,1550.0
13,1002,2018-09,36.0,206.0,4.0,16691.08,Евгений,Абрамович,smart,950.0
14,1002,2018-10,33.0,212.0,10.0,13888.25,Евгений,Абрамович,smart,550.0
15,1002,2018-11,32.0,243.0,16.0,18587.28,Евгений,Абрамович,smart,1350.0
16,1002,2018-12,33.0,236.0,12.0,18113.73,Евгений,Абрамович,smart,1150.0
17,1003,2018-08,55.0,380.0,37.0,8565.21,Белла,Белякова,ultra,1950.0
18,1003,2018-09,134.0,961.0,91.0,12468.87,Белла,Белякова,ultra,1950.0
19,1003,2018-10,108.0,855.0,83.0,14768.14,Белла,Белякова,ultra,1950.0
20,1003,2018-11,115.0,824.0,94.0,11356.89,Белла,Белякова,ultra,1950.0
21,1003,2018-12,108.0,802.0,75.0,10121.53,Белла,Белякова,ultra,1950.0
22,1004,2018-05,9.0,35.0,95.0,13403.98,Татьяна,Авдеенко,ultra,1950.0
23,1004,2018-06,31.0,171.0,134.0,17600.02,Татьяна,Авдеенко,ultra,1950.0
24,1004,2018-07,22.0,135.0,181.0,22229.58,Татьяна,Авдеенко,ultra,1950.0
25,1004,2018-08,19.0,137.0,151.0,28584.37,Татьяна,Авдеенко,ultra,1950.0
26,1004,2018-09,26.0,117.0,146.0,15109.03,Татьяна,Авдеенко,ultra,1950.0
27,1004,2018-10,29.0,145.0,165.0,18475.44,Татьяна,Авдеенко,ultra,1950.0
28,1004,2018-11,19.0,117.0,158.0,15616.02,Татьяна,Авдеенко,ultra,1950.0
29,1004,2018-12,21.0,130.0,162.0,18021.04,Татьяна,Авдеенко,ultra,1950.0
30,1005,2018-01,15.0,95.0,7.0,2727.97,Афанасий,Горлов,smart,550.0
31,1005,2018-02,69.0,456.0,38.0,7383.93,Афанасий,Горлов,smart,550.0
32,1005,2018-03,77.0,606.0,56.0,11104.25,Афанасий,Горлов,smart,886.0
33,1005,2018-04,101.0,712.0,41.0,9351.72,Афанасий,Горлов,smart,1186.0
34,1005,2018-05,73.0,595.0,42.0,7865.53,Афанасий,Горлов,smart,835.0
35,1005,2018-06,80.0,612.0,47.0,9863.19,Афанасий,Горлов,smart,886.0
36,1005,2018-07,77.0,569.0,56.0,7694.56,Афанасий,Горлов,smart,775.0
37,1005,2018-08,71.0,619.0,64.0,7543.63,Афанасий,Горлов,smart,949.0
38,1005,2018-09,66.0,479.0,52.0,7016.46,Афанасий,Горлов,smart,556.0
39,1005,2018-10,100.0,723.0,44.0,7800.93,Афанасий,Горлов,smart,1219.0
40,1005,2018-11,75.0,547.0,51.0,12666.95,Афанасий,Горлов,smart,694.0
41,1005,2018-12,84.0,592.0,54.0,8668.19,Афанасий,Горлов,smart,838.0
42,1006,2018-02,3.0,42.0,0.0,1392.15,Леонид,Ермолаев,smart,550.0
43,1006,2018-03,46.0,286.0,0.0,17287.93,Леонид,Ермолаев,smart,950.0
44,1006,2018-04,47.0,356.0,0.0,13936.70,Леонид,Ермолаев,smart,550.0
45,1006,2018-05,56.0,370.0,0.0,12965.41,Леонид,Ермолаев,smart,550.0
46,1006,2018-06,53.0,478.0,0.0,12371.66,Леонид,Ермолаев,smart,550.0
47,1006,2018-07,49.0,316.0,0.0,19977.60,Леонид,Ермолаев,smart,1550.0
48,1006,2018-08,42.0,275.0,0.0,19303.71,Леонид,Ермолаев,smart,1350.0
49,1006,2018-09,54.0,360.0,0.0,15521.53,Леонид,Ермолаев,smart,750.0

In [64]:
df['monthly_profit_each_user'].sum()

4914451.0

In [65]:
dict_to_df = {'col1': [1,2,3,4,5],
              'col2': [6,7,8,9,10],
              'col3': [16,17,18,19,20],
              'cat': ['Студент', 'Преподаватель', 'Студент', 'Преподаватель', 'Студент']}

In [67]:
df2 = pd.DataFrame(dict_to_df)

In [68]:
df2

   col1  col2  col3            cat
0     1     6    16        Студент
1     2     7    17  Преподаватель
2     3     8    18        Студент
3     4     9    19  Преподаватель
4     5    10    20        Студент

In [72]:
def g(name_df):
    if name_df['cat'] == 'Студент':
        return name_df['col1'] + name_df['col2'] + name_df['col3']
    else:
        return name_df['col1'] - name_df['col2'] - name_df['col3']

In [75]:
df2.apply(g, axis=1)

0    23
1   -22
2    29
3   -24
4    35
dtype: int64

In [69]:
def f(x):
    if x <=3:
        return 'Плохо'
    else:
        return 'Хорошо'

In [70]:
df2.col1.apply(f)

0     Плохо
1     Плохо
2     Плохо
3    Хорошо
4    Хорошо
Name: col1, dtype: object